### ISSUE TITLE
Not working link to documentation

### ISSUE THREAD

**Issue by racinmat** [Kdyby/Money#20]
https://github.com/Kdyby/Money/blob/master/docs/en/index.md
This link does not work, I would really appreciate if you provided documentation, 
I would like to use this library and I really miss documentation.

**Comment by simPod** [comment]
What is this library event used for?

**Comment by fprochazka** [comment]
@simPod I'm confused, what event do you have in mind?

**Comment by simPod** [comment]
@fprochazka should have been "even". Sorry, autocorrect

**Comment by fprochazka** [comment]
@simPod it's a value object representing money with currency in our application.

**Comment by HonzaMac** [comment]
Where is doc?
